// The one place every LeadPack Photos query is scoped by team_id — build
// spec, "Privacy and guardrails": "Every query and every URL-issuing route
// is scoped by team_id. Put this check in one shared data-access helper,
// not in each route, because LeadPack is planned for licensing to other
// teams and a cross-team leak is the worst failure here."
//
// A route handler must never call prisma.photo.* / prisma.photoAthlete.* /
// prisma.pick.* / prisma.collage.* directly — it calls into this module,
// and teamId always comes from req.user.teamId (set by middleware/auth.js
// from the verified session), never from a request param or body.

const crypto = require('crypto');
const { hasTeamRole } = require('../middleware/auth');
const { ANY_COACH } = require('./teamRoles');
const { resolveActiveSeason, isAthleteOnSeasonRoster } = require('./season');
const { authorizeTag, canManageAthlete, canRemoveTag, canHidePhoto } = require('./photoTagRules');
const r2 = require('./r2');

const MAX_PICKS = 5;

// --- Actor resolution -------------------------------------------------

/**
 * Builds the PhotoActor for this request: coach-ness via the same
 * TeamMember role check every other route uses, plus this account's own
 * linked athlete and any athletes it holds an APPROVED GuardianLink for —
 * both scoped to `teamId`, never to `user.teamId` directly. The two differ
 * for a guardian account: a parent is never a TeamMember (routes/guardian.js),
 * so `user.teamId` is null for them and the caller (routes/photos.js's
 * resolvePhotosTeam) has already worked out which team their approved link
 * actually belongs to.
 */
async function resolveActor(prisma, user, teamId) {
  const isCoach = Boolean((user.isSuperAdmin && user.isImpersonating) || (await hasTeamRole(user, ANY_COACH)));

  // A coach's authority already covers every athlete (authorizeTag checks
  // isCoach first) — skip the guardian-link lookup entirely rather than
  // run a query whose result can never change the outcome.
  if (isCoach) {
    return { userId: user.id, isCoach: true, selfAthleteId: null, guardianAthleteIds: [], linkedAthleteIds: [] };
  }

  const selfAthleteId = user.linkedAthlete && user.linkedAthlete.teamId === teamId ? user.linkedAthlete.id : null;

  const guardianLinks = await prisma.guardianLink.findMany({
    where: { userId: user.id, status: 'approved', athlete: { teamId } },
    select: { athleteId: true },
  });
  const guardianAthleteIds = guardianLinks.map((l) => l.athleteId);

  const linkedAthleteIds = Array.from(new Set([selfAthleteId, ...guardianAthleteIds].filter(Boolean)));

  return { userId: user.id, isCoach, selfAthleteId, guardianAthleteIds, linkedAthleteIds };
}

// --- Single-photo lookups ----------------------------------------------

// Returns null both when the id doesn't exist and when it belongs to
// another team — those two cases must look identical to the caller, so a
// cross-team id can never be distinguished from a typo.
async function getTeamPhoto(prisma, teamId, photoId) {
  return prisma.photo.findFirst({ where: { id: photoId, teamId } });
}

async function findExistingByHash(prisma, teamId, sha256) {
  return prisma.photo.findFirst({ where: { teamId, sha256 } });
}

// --- Upload: authorize / finalize (Phase 3) ----------------------------

// The server, not the browser, decides a photo_id and inserts the row
// before any bytes move — see the build spec's upload pipeline: "The
// photo_id is generated by the server when the upload is authorized, and
// the same value is used in the key and the photos row." The id is
// generated here (not left to Prisma's default) because the object key
// the row stores is itself derived from that id, and objectKey is a
// required, unique column — there's no not-yet-known placeholder to write.
async function createPendingPhoto(prisma, { teamId, meetId, sha256, uploadedById, takenAt, width, height, bytes }) {
  const id = crypto.randomUUID();
  const objectKey = r2.photoOriginalKey(teamId, id);
  return prisma.photo.create({
    data: {
      id,
      teamId,
      meetId,
      objectKey,
      sha256,
      uploadedBy: uploadedById,
      status: 'PENDING',
      takenAt: takenAt ? new Date(takenAt) : null,
      width: width ?? null,
      height: height ?? null,
      bytes: bytes != null ? BigInt(bytes) : null,
    },
  });
}

/**
 * Authorize step: for each file, skip ones whose (team_id, sha256) already
 * exists (dedupe), else insert a `pending` row and return presigned PUT
 * URLs for its three objects. `meetId` is verified to belong to this team
 * before any row is created.
 *
 * An existing row stuck at PENDING is a previous upload that never
 * finished (the browser closed, a PUT failed) — not a real duplicate, and
 * `(teamId, sha256)` being a hard DB unique constraint means there's no
 * way to insert a second row for the same hash to retry with. So this
 * hands back fresh presigned PUT URLs for that same existing row instead
 * of `duplicate: true`, which would otherwise leave it stuck at PENDING,
 * invisible in every grid, forever — see importReadyPhoto below for the
 * same bug in the Google Photos import path, where it actually happened.
 */
async function authorizeUpload(prisma, { teamId, meetId, uploadedById, files }) {
  const meet = await prisma.meet.findFirst({ where: { id: meetId, teamId } });
  if (!meet) {
    const err = new Error('Meet not found.');
    err.statusCode = 404;
    throw err;
  }

  const results = [];
  for (const file of files) {
    const existing = await findExistingByHash(prisma, teamId, file.sha256);
    if (existing && existing.status !== 'PENDING') {
      results.push({ photoId: existing.id, duplicate: true, putUrls: null });
      continue;
    }

    const photo =
      existing ||
      (await createPendingPhoto(prisma, {
        teamId,
        meetId,
        sha256: file.sha256,
        uploadedById,
        takenAt: file.takenAt,
        width: file.width,
        height: file.height,
        bytes: file.bytes,
      }));

    const [originalPutUrl, thumbPutUrl, webPutUrl] = await Promise.all([
      r2.presignPutUrl(photo.objectKey, 'image/jpeg'),
      r2.presignPutUrl(r2.photoThumbKey(teamId, photo.id), 'image/webp'),
      r2.presignPutUrl(r2.photoWebKey(teamId, photo.id), 'image/webp'),
    ]);

    results.push({
      photoId: photo.id,
      duplicate: false,
      putUrls: { original: originalPutUrl, thumb: thumbPutUrl, web: webPutUrl },
    });
  }
  return results;
}

// Finalize step: flips a photo to ready only if it both exists AND belongs
// to this team — the `where` clause is the enforcement, not a check
// beforehand that something else could race past. Confirms all three R2
// objects actually landed before flipping — never trusts the browser's own
// say-so that the PUTs succeeded.
async function finalizeTeamPhoto(prisma, teamId, photoId) {
  const photo = await getTeamPhoto(prisma, teamId, photoId);
  if (!photo) return { ok: false, reason: 'not_found' };
  if (photo.status === 'READY') return { ok: true, alreadyReady: true };
  if (photo.status !== 'PENDING') return { ok: false, reason: 'not_pending' };

  const [origOk, thumbOk, webOk] = await Promise.all([
    r2.objectExists(r2.photoOriginalKey(teamId, photoId)),
    r2.objectExists(r2.photoThumbKey(teamId, photoId)),
    r2.objectExists(r2.photoWebKey(teamId, photoId)),
  ]);
  if (!origOk || !thumbOk || !webOk) {
    return { ok: false, reason: 'incomplete', missing: { original: !origOk, thumb: !thumbOk, web: !webOk } };
  }

  const result = await prisma.photo.updateMany({
    where: { id: photoId, teamId, status: 'PENDING' },
    data: { status: 'READY' },
  });
  return { ok: result.count > 0 };
}

// --- Listing / visibility ------------------------------------------------

/**
 * Every READY (or, for a coach only, HIDDEN) photo for this team, with its
 * tags, filtered by the spec's rule 4: a photo tagged with an opted-out
 * athlete disappears from every grid except the coach's.
 */
async function listTeamPhotos(prisma, teamId, actor, { meetId, includeHidden } = {}) {
  const status = includeHidden ? 'HIDDEN' : 'READY';
  if (includeHidden && !actor.isCoach) {
    const err = new Error('Only a coach can view hidden photos.');
    err.statusCode = 403;
    throw err;
  }

  const photos = await prisma.photo.findMany({
    where: { teamId, status, ...(meetId ? { meetId } : {}) },
    include: { tags: true },
    orderBy: { takenAt: 'asc' },
  });

  if (actor.isCoach) return photos;

  const optedOut = await prisma.athlete.findMany({ where: { teamId, photosOptOut: true }, select: { id: true } });
  const optedOutIds = new Set(optedOut.map((a) => a.id));
  return photos.filter((p) => !p.tags.some((t) => optedOutIds.has(t.athleteId)));
}

async function listPicksForTeam(prisma, teamId, seasonId) {
  const picks = await prisma.pick.findMany({
    where: { seasonId, athlete: { teamId } },
    orderBy: { position: 'asc' },
  });
  const byAthlete = new Map();
  for (const pick of picks) {
    const list = byAthlete.get(pick.athleteId) ?? [];
    list.push(pick);
    byAthlete.set(pick.athleteId, list);
  }
  return byAthlete;
}

// --- Tagging (Phase 4) ---------------------------------------------------

async function tagPhoto(prisma, teamId, photoId, athleteId, actor) {
  const { allowed, source } = authorizeTag(actor, athleteId);
  if (!allowed) {
    const err = new Error('This account cannot tag that athlete.');
    err.statusCode = 403;
    throw err;
  }

  const photo = await getTeamPhoto(prisma, teamId, photoId);
  if (!photo) {
    const err = new Error('Photo not found.');
    err.statusCode = 404;
    throw err;
  }
  const athlete = await prisma.athlete.findFirst({ where: { id: athleteId, teamId } });
  if (!athlete) {
    const err = new Error('Athlete not found.');
    err.statusCode = 404;
    throw err;
  }
  // Tagging is locked to the current season's roster, not everyone who
  // has ever worn the uniform — a graduated senior from three seasons ago
  // showing up in the armed-athlete search was the actual bug report.
  const seasonYear = await resolveActiveSeason(teamId);
  if (!(await isAthleteOnSeasonRoster(athleteId, teamId, seasonYear))) {
    const err = new Error('That athlete is not on this season\'s roster.');
    err.statusCode = 409;
    throw err;
  }

  return prisma.photoAthlete.upsert({
    where: { photoId_athleteId: { photoId, athleteId } },
    update: {},
    create: { photoId, athleteId, taggedBy: actor.userId, source },
  });
}

async function untagPhoto(prisma, teamId, photoId, athleteId, actor) {
  const photo = await getTeamPhoto(prisma, teamId, photoId);
  if (!photo) {
    const err = new Error('Photo not found.');
    err.statusCode = 404;
    throw err;
  }
  const tag = await prisma.photoAthlete.findUnique({ where: { photoId_athleteId: { photoId, athleteId } } });
  if (!tag) return { ok: true, removed: false };
  if (!canRemoveTag(actor, tag)) {
    const err = new Error('This account cannot remove that tag.');
    err.statusCode = 403;
    throw err;
  }
  // Cascades to any Pick built on this (photo, athlete) tag — the same
  // composite FK that stops a pick being created without one.
  await prisma.photoAthlete.delete({ where: { photoId_athleteId: { photoId, athleteId } } });
  return { ok: true, removed: true };
}

/**
 * Where this athlete's collage crop should center on this photo — the
 * Build module's "move the photo to see faces" drag. Lives on the tag
 * itself (not Pick) so a reposition survives the photo being swapped out
 * of a slot and back in. Same authorization as setPicks: a coach, or the
 * athlete's own linked guardian/self account — never a volunteer tagging
 * session.
 */
async function setPhotoFocal(prisma, teamId, photoId, athleteId, focalX, focalY, actor) {
  if (!canManageAthlete(actor, athleteId)) {
    const err = new Error('This account cannot reposition that photo.');
    err.statusCode = 403;
    throw err;
  }
  const photo = await getTeamPhoto(prisma, teamId, photoId);
  if (!photo) {
    const err = new Error('Photo not found.');
    err.statusCode = 404;
    throw err;
  }
  const tag = await prisma.photoAthlete.findUnique({ where: { photoId_athleteId: { photoId, athleteId } } });
  if (!tag) {
    const err = new Error('That athlete is not tagged in this photo.');
    err.statusCode = 404;
    throw err;
  }
  const clamp = (n) => Math.min(1, Math.max(0, n));
  return prisma.photoAthlete.update({
    where: { photoId_athleteId: { photoId, athleteId } },
    data: { focalX: clamp(focalX), focalY: clamp(focalY) },
  });
}

// --- Picks (Phase 5) ------------------------------------------------------

async function resolveActiveSeasonRow(prisma, teamId) {
  const year = await resolveActiveSeason(teamId);
  const season = await prisma.season.findFirst({ where: { teamId, year } });
  if (!season) {
    const err = new Error('No season is set up for this team yet.');
    err.statusCode = 409;
    throw err;
  }
  return season;
}

/**
 * Replaces an athlete's full pick list for a season in one transaction —
 * simpler and safer than diffing individual position swaps/reorders, and
 * exactly what the Build module's reorder/swap/add/remove all reduce to
 * client-side already (one ordered array of photo ids).
 *
 * Silently drops any photoId the athlete isn't actually tagged in (rule 5)
 * and caps at MAX_PICKS, mirroring the frontend's own canPickPhoto gate
 * rather than erroring on a list the client should never have produced.
 */
async function setPicks(prisma, teamId, athleteId, photoIds, actor) {
  if (!canManageAthlete(actor, athleteId)) {
    const err = new Error('This account cannot set picks for that athlete.');
    err.statusCode = 403;
    throw err;
  }
  const athlete = await prisma.athlete.findFirst({ where: { id: athleteId, teamId } });
  if (!athlete) {
    const err = new Error('Athlete not found.');
    err.statusCode = 404;
    throw err;
  }

  const season = await resolveActiveSeasonRow(prisma, teamId);

  const uniqueIds = Array.from(new Set(photoIds)).slice(0, MAX_PICKS);
  const tags = uniqueIds.length
    ? await prisma.photoAthlete.findMany({ where: { athleteId, photoId: { in: uniqueIds } } })
    : [];
  const taggedSet = new Set(tags.map((t) => t.photoId));
  const validIds = uniqueIds.filter((id) => taggedSet.has(id));

  await prisma.$transaction([
    prisma.pick.deleteMany({ where: { athleteId, seasonId: season.id } }),
    ...validIds.map((photoId, index) =>
      prisma.pick.create({ data: { athleteId, seasonId: season.id, photoId, position: index + 1 } }),
    ),
  ]);

  return prisma.pick.findMany({ where: { athleteId, seasonId: season.id }, orderBy: { position: 'asc' } });
}

// --- Hide / unhide / delete (Phase 4/6) -----------------------------------

async function setPhotoHidden(prisma, teamId, photoId, hidden, actor) {
  if (!canHidePhoto(actor)) {
    const err = new Error('Only a coach can hide or unhide a photo.');
    err.statusCode = 403;
    throw err;
  }
  const photo = await getTeamPhoto(prisma, teamId, photoId);
  if (!photo) {
    const err = new Error('Photo not found.');
    err.statusCode = 404;
    throw err;
  }
  const nextStatus = hidden ? 'HIDDEN' : 'READY';
  return prisma.photo.update({ where: { id: photoId }, data: { status: nextStatus } });
}

async function deleteTeamPhoto(prisma, teamId, photoId, actor) {
  if (!canHidePhoto(actor)) {
    const err = new Error('Only a coach can delete a photo.');
    err.statusCode = 403;
    throw err;
  }
  const photo = await getTeamPhoto(prisma, teamId, photoId);
  if (!photo) {
    const err = new Error('Photo not found.');
    err.statusCode = 404;
    throw err;
  }

  await Promise.all(
    [r2.photoOriginalKey(teamId, photoId), r2.photoThumbKey(teamId, photoId), r2.photoWebKey(teamId, photoId)].map(
      (key) => r2.deleteObject(key).catch(() => {}), // best-effort: a missing object (e.g. a pending upload that never finished) is not a reason to fail the delete
    ),
  );
  await prisma.photo.delete({ where: { id: photoId } });
  return { ok: true };
}

// --- Opt-out (Phase 6) -----------------------------------------------------

async function setAthleteOptOut(prisma, teamId, athleteId, optOut, actor) {
  if (!actor.isCoach && !canManageAthlete(actor, athleteId)) {
    const err = new Error('This account cannot change that athlete\'s photo opt-out.');
    err.statusCode = 403;
    throw err;
  }
  const athlete = await prisma.athlete.findFirst({ where: { id: athleteId, teamId } });
  if (!athlete) {
    const err = new Error('Athlete not found.');
    err.statusCode = 404;
    throw err;
  }
  return prisma.athlete.update({ where: { id: athleteId }, data: { photosOptOut: Boolean(optOut) } });
}

// --- Download (an athlete's own folder) -------------------------------------

/**
 * Every READY, non-hidden photo this athlete is tagged in — the "download
 * my athlete's folder" feature (routes/photos.js streams these originals
 * into a ZIP). Coach or the athlete's own linked account only, same
 * authority as picks/opt-out — deliberately NOT available to a volunteer
 * session (lib/photoTagRules.js's isVolunteer only ever unlocks tagging).
 *
 * An opted-out athlete can still download their own photos — opt-out
 * means "don't show me to other people's grids," not "deny this family
 * their own pictures" — so this does not check photosOptOut at all.
 */
async function listAthletePhotosForDownload(prisma, teamId, athleteId, actor) {
  if (!actor.isCoach && !canManageAthlete(actor, athleteId)) {
    const err = new Error('This account cannot download that athlete\'s photos.');
    err.statusCode = 403;
    throw err;
  }
  const athlete = await prisma.athlete.findFirst({ where: { id: athleteId, teamId }, select: { id: true } });
  if (!athlete) {
    const err = new Error('Athlete not found.');
    err.statusCode = 404;
    throw err;
  }
  return prisma.photo.findMany({
    where: { teamId, status: 'READY', tags: { some: { athleteId } } },
    select: { id: true, objectKey: true, takenAt: true, meet: { select: { name: true } } },
    orderBy: { takenAt: 'asc' },
  });
}

// --- Import (Google Photos album) -----------------------------------------

/**
 * Creates a photo row directly as READY from bytes the server already has
 * in hand (lib/googlePhotosImport.js). Unlike the browser upload path
 * (authorize -> presigned PUT -> finalize), there is no separate client to
 * hand a presigned URL to — the server downloaded the original itself, so
 * it uploads all three objects itself too, and marks the row ready right
 * away rather than re-checking R2 for what it just wrote.
 *
 * A real bug this already hit in production: `(teamId, sha256)` is a hard
 * DB unique constraint (schema.prisma), so the row has to be created
 * *before* the R2 writes below, with no way to insert it again later if
 * those writes fail. The first time an R2 write failed partway (an R2
 * credential problem, in the one real case so far), the row it already
 * created was left stuck at PENDING forever — and every later re-import
 * found that same row by hash and reported it as an ordinary duplicate,
 * without ever checking it actually had real R2 objects behind it. That's
 * what "188 already had, 0 failed" with nothing actually visible in the
 * Tag module turned out to mean: a stuck PENDING row isn't a photo, but
 * nothing here knew the difference.
 *
 * So an existing PENDING row (as opposed to READY or HIDDEN, both of
 * which really do mean "this photo is already here") is treated as an
 * interrupted previous attempt, not a duplicate — this resumes it, using
 * that same row's id and object key, instead of trying to insert a second
 * row for the same hash and hitting the unique constraint. Idempotent
 * either way: re-writing the same three R2 objects for a row that did
 * make it to READY last time around has no bad effect, since they're
 * last-write-wins keyed by this row's own id.
 */
async function importReadyPhoto(prisma, { teamId, meetId, uploadedById, originalBuffer, thumbBuffer, webBuffer, sha256, width, height }) {
  const existing = await findExistingByHash(prisma, teamId, sha256);
  if (existing && existing.status !== 'PENDING') {
    return { duplicate: true, photoId: existing.id };
  }

  const photo = existing || (await createPendingPhoto(prisma, { teamId, meetId, sha256, uploadedById, width, height }));

  await Promise.all([
    r2.putObject(photo.objectKey, originalBuffer, 'image/jpeg'),
    r2.putObject(r2.photoThumbKey(teamId, photo.id), thumbBuffer, 'image/webp'),
    r2.putObject(r2.photoWebKey(teamId, photo.id), webBuffer, 'image/webp'),
  ]);

  await prisma.photo.update({ where: { id: photo.id }, data: { status: 'READY' } });
  return { duplicate: false, photoId: photo.id };
}

module.exports = {
  MAX_PICKS,
  resolveActor,
  getTeamPhoto,
  findExistingByHash,
  createPendingPhoto,
  authorizeUpload,
  finalizeTeamPhoto,
  listTeamPhotos,
  listPicksForTeam,
  tagPhoto,
  untagPhoto,
  setPhotoFocal,
  resolveActiveSeasonRow,
  setPicks,
  setPhotoHidden,
  deleteTeamPhoto,
  setAthleteOptOut,
  importReadyPhoto,
  listAthletePhotosForDownload,
};
